### ISSUE TITLE
peer to peer code review

### ISSUE THREAD

**Issue by Kumilachew-g** [carlosmuerto/Portfolio#16]
You have done great tasks.
- [x] 1-When you click on the mobile menu it should indicate an active
- [x] 2-About me text should be centered and give padding-margin

**Comment by limavfabio** [comment]
Your portfolio is looking awesome Carlos! But I believe the Javascript files are not loading properly on the index, maybe you could give it a look and see if you can fix it. The error that appears to me:

Access to script at 'file:///home/limavfabio/Documents/Portfolio-popup-modal/js/index.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, brave, chrome-untrusted, https.
index.js:1          Failed to load resource: net::ERR_FAILED
index.html:1 Access to script at 'file:///home/limavfabio/Documents/Portfolio-popup-modal/js/works.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, brave, chrome-untrusted, https.
works.js:1          Failed to load resource: net::ERR_FAILED
