### ISSUE TITLE
Portfolio already deployed before activity

### ISSUE THREAD

**Issue by carlosmuerto** [carlosmuerto/Portfolio#8]
# Portfolio: application deploy

as the [activity](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/5_deploy.md) says I should open an issue in case of already deployed before.

## Important links:
> - [Repository](https://github.com/carlosmuerto/Portfolio)
> - [README.md](https://github.com/carlosmuerto/Portfolio/blob/main/README.md)
> - **[Portfolio Page](https://carlosmuerto.github.io/Portfolio/)**

**Comment by topeogunleye** [comment]
### **STATUS: APPROVED  ✔️** 
------
Hi @carlosmuerto,  

Your project is complete! Great job for nailing it right on the first attempt 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)

## To highlight :champagne: 
- Deployed application :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Issue has a good title and description :heavy_check_mark:
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
