### ISSUE TITLE
Figures images should be not be mixing witht he footer line container

### ISSUE THREAD

**Issue by armandocomellas1** [carlosmuerto/Portfolio#9]
Good job so far! we as a pair group team recommend you put higher figures into your project.

**Comment by carlosmuerto** [comment]
## from this 
 > ![imagen](https://user-images.githubusercontent.com/34493013/178514667-fdc7c856-e10e-43be-9ba5-23fa5f6d9c93.png)


## to this
 > ![imagen](https://user-images.githubusercontent.com/34493013/178514795-f9fd714e-945c-411c-97f3-f27ebeb8a8a8.png)

**Comment by joa-byte** [comment]
## Hey Carlos, your code looks fantastic!

- Your animations are impressive
- Your code is great written

There's only one thing calling my attention and it's that the button for the form at the end doesn't match the Figma template. Cheers and happy coding!
